# Log Processing Configuration
log_processing:
  timestamp_format: "%Y-%m-%d %H:%M:%S"

# Chunking Configuration
chunking:
  chunk_size: 200  # Reduced for individual log entries
  chunk_overlap: 50  # Reduced overlap
  separator: "\n"
  use_individual_logs: true  # New: prioritize individual log entries
  max_combined_logs: 10  # New: limit combined context chunks

# Embedding Configuration
embedding:
  model_type: "auto"  # Options: "google", "sentence_transformers", "auto"
  model_name: "models/embedding-001"  # Google model name or sentence-transformers model
  batch_size: 100
  # Sentence Transformers specific settings
  sentence_transformers:
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    device: "auto"  # "cpu", "cuda", or "auto"

# Vector Store Configuration
vector_store:
  type: "chroma"  # Options: "chroma", "qdrant", "auto" (prefers Qdrant)
  collection_name: "log_embeddings"
  persist_directory: "./data/vector_store"
  version: "1.0.0"
  
  # Qdrant specific settings
  qdrant:
    host: "localhost"
    port: 6333
    url: null  # Use this for Qdrant Cloud: "https://your-cluster.qdrant.io"
    api_key: null  # API key for Qdrant Cloud
    vector_size: 384  # Will be auto-detected from embedding model
    
  # Chroma specific settings (fallback)
  chroma:
    persist_directory: "./data/vector_store"

# Search Configuration
search:
  similarity_threshold: 0.7  # Filter results above this distance (increased from 0.4 to be more permissive)
  max_results: 10
  include_combined_chunks: false  # Focus on individual log matches
  boost_exact_matches: true  # Prioritize exact keyword matches

# LLM Configuration
llm:
  model_name: "gemini-1.5-pro"
  temperature: 0.1
  max_output_tokens: 512
  top_p: 0.8
  top_k: 40
  safety_settings:
    - category: "HARM_CATEGORY_HARASSMENT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_HATE_SPEECH"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
