# Log Processing Configuration
log_processing:
  timestamp_format: "%Y-%m-%d %H:%M:%S"

# Chunking Configuration
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  separator: "\n"

# Embedding Configuration
embedding:
  model_name: "models/embedding-001"  # Google's text embedding model
  batch_size: 100

# Vector Store Configuration
vector_store:
  collection_name: "log_embeddings"
  persist_directory: "./data/vector_store"

# LLM Configuration
llm:
  model_name: "gemini-1.5-pro"
  temperature: 0.1
  max_output_tokens: 2048
  top_p: 0.8
  top_k: 40
  safety_settings:
    - category: "HARM_CATEGORY_HARASSMENT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_HATE_SPEECH"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
    - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
      threshold: "BLOCK_MEDIUM_AND_ABOVE"
